name: QA Deployer

on:
  push:
    branches:
      - main

concurrency:
  group: qa-deployment
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: build
      run: |
        echo "Building"
        sleep 3m
