name: PR Validator

on:
  pull_request:

jobs:
  build_and_test:
    name: Build and run unit tests
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Validate
        run: |
          echo "Validating..."
          sleep 2m
